### ISSUE TITLE
gh.vercte.net No longer brings you to Forumoji

### ISSUE THREAD

**Issue by Steve0Greatness** [vercte/forumoji#80]
Forumoji is no longer showing up when you go to [`https://vercte.github.io/forumoji/`](https://vercte.github.io/forumoji/). At least for me: It's only bringing up a 404.

@vercte I swear your username used to be loptse, did you change it recently? If so: that might be why.

**Comment by vercte** [comment]
yeah i’ll fix that. got tired of having two different usernames so changed
it to vercte

**Comment by Steve0Greatness** [comment]
Thank! I'll close this as completed as this problem appears to be fixed(Forumoji is no longer giving a 404).
